import React, { useEffect, useState } from "react";
import { FileSearch, RefreshCw } from "lucide-react";
import { getRiskEvents } from "../api/adminApi";
import AdminLayout from "../components/layout/AdminLayout";
import AdminHeader from "../components/layout/AdminHeader";
import RiskBadge from "../components/dashboard/RiskBadge";

export default function RiskEventsPage() {
  const [riskEvents, setRiskEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");

  const loadRiskEvents = async (silent = false) => {
    try {
      setError("");
      if (silent) setRefreshing(true);
      else setLoading(true);

      const res = await getRiskEvents();
      setRiskEvents(res.riskEvents || []);
    } catch (err) {
      setError(err.message || "Failed to load risk events");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadRiskEvents();
  }, []);

  return (
    <AdminLayout>
      <AdminHeader
        title="Risk Events"
        subtitle="Inspect anomaly signals and fraud indicators generated by the ML service during voting activity."
      />

      {error ? (
        <div className="mb-6 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
          {error}
        </div>
      ) : null}

      <div className="mb-6 flex justify-end">
        <button
          onClick={() => loadRiskEvents(true)}
          className="inline-flex items-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white"
        >
          <RefreshCw className={`h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />
          Refresh Events
        </button>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-4">
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-1">
          <div className="mb-4 flex items-center gap-3">
            <div className="rounded-2xl bg-slate-100 p-3">
              <FileSearch className="h-5 w-5 text-slate-700" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">Event Insights</h2>
              <p className="text-sm text-slate-500">Machine-generated anomaly activity.</p>
            </div>
          </div>

          <div className="space-y-4">
            <div className="rounded-2xl bg-slate-50 p-4">
              <h3 className="font-semibold text-slate-900">Low Risk</h3>
              <p className="mt-2 text-sm text-slate-600">
                Routine events with minimal suspicious indicators.
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <h3 className="font-semibold text-slate-900">Medium Risk</h3>
              <p className="mt-2 text-sm text-slate-600">
                Events that should be monitored or correlated with other signals.
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <h3 className="font-semibold text-slate-900">High Risk</h3>
              <p className="mt-2 text-sm text-slate-600">
                Events likely associated with suspicious voting behavior and manual review.
              </p>
            </div>
          </div>
        </div>

        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-3">
          {loading ? (
            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-8 text-center text-sm text-slate-500">
              Loading risk events...
            </div>
          ) : (
            <div className="overflow-hidden rounded-2xl border border-slate-200">
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-slate-200 text-sm">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Voter</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Election</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Event Type</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Risk Level</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Flags</th>
                      <th className="px-4 py-3 text-left font-semibold text-slate-600">Date</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 bg-white">
                    {riskEvents.map((event) => (
                      <tr key={event._id} className="hover:bg-slate-50">
                        <td className="px-4 py-4">
                          <div className="font-medium text-slate-900">
                            {event.voterId?.fullName || "Unknown voter"}
                          </div>
                          <div className="text-xs text-slate-500">
                            {event.voterId?.email || "No email"}
                          </div>
                        </td>
                        <td className="px-4 py-4 text-slate-700">
                          {event.electionId?.title || "Unknown election"}
                        </td>
                        <td className="px-4 py-4 capitalize text-slate-700">
                          {event.eventType || "unknown"}
                        </td>
                        <td className="px-4 py-4">
                          <RiskBadge level={event.riskLevel} />
                        </td>
                        <td className="px-4 py-4 text-slate-600">
                          <div className="flex flex-wrap gap-2">
                            {(event.flags || []).length > 0 ? (
                              event.flags.map((flag, index) => (
                                <span
                                  key={`${event._id}-${index}`}
                                  className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-medium text-slate-600"
                                >
                                  {flag}
                                </span>
                              ))
                            ) : (
                              <span className="text-xs text-slate-400">No flags</span>
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-4 text-slate-500">
                          {new Date(event.createdAt).toLocaleString()}
                        </td>
                      </tr>
                    ))}

                    {riskEvents.length === 0 ? (
                      <tr>
                        <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                          No risk events found.
                        </td>
                      </tr>
                    ) : null}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </AdminLayout>
  );
}